### ISSUE TITLE
unhandled exception in check_mk when using neamon core

### ISSUE THREAD

**Issue by kafos** [ConSol/omd#49] opened 2017-09-15 13:10 UTC
Using naemon core is showing an error in check_mk:
Local site xxxx - Livestatus error
Unhandled exception: 400: Table 'hosts' has no column 'host_comments_with_extra_info'

Ubuntu Server 16.04 
OMD 2.60

**Comment by AllwynPradip** [comment] 2017-11-07 11:06
#42

**Comment by sni** [comment] 2018-07-02 08:06
duplicate of #42

**Closed as completed by sni** 2018-07-02 08:06 UTC
