### ISSUE TITLE
Error in performance graph after OMD upgrade to 5.00

### ISSUE THREAD

**Issue by Vani2468** [ConSol/omd#147] opened 2023-01-04 16:57 UTC
Hi,

We have upgraded OMD from omd-4.61 to omd-5.00, After upgrade we have observed that performance graph on any service is displaying with attached error message.

Error message: ERROR: STDOUT => ERROR: Invalid option -- 'lower=0'

![image](https://user-images.githubusercontent.com/121673444/210607584-edb10904-eb4d-4a14-85fc-52a258546c00.png)

Kindly advice how to fix the error in performance graphs.

**Comment by sni** [comment] 2023-01-04 20:41
duplicate of #143

**Comment by sni** [comment] 2023-01-04 20:41
You could update to the daily version, it is fixed already.

**Closed as completed by sni** 2023-01-04 20:41 UTC
