### ISSUE TITLE
check_mk lacks database fields

### ISSUE THREAD

**Issue by roflmao** [ConSol/omd#9] opened 2015-02-23 14:08 UTC
omd-newcores-2.00:

Livestatus problem: Unhandled exception: 400: Table 'hosts' has no column 'host_comments_with_extra_info'

Livestatus problem: Unhandled exception: 400: Table 'services' has no column 'service_comments_with_extra_info'

**Comment by sni** [comment] 2015-05-25 09:13
duplicate of #4

**Closed by sni** 2015-05-25 09:13 UTC
